/* eslint-disable import/no-anonymous-default-export */
export default {
  h1: {
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "64px",
    lineHeight: "74px",
    letterSpacing: "-0.01em",
  },
  h2: {
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "28px",
    lineHeight: "42px",
    letterSpacing: "-0.01em",
  },
  h3: {
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "22px",
    lineHeight: "32px",
    letterSpacing: "-0.02em",
  },
  h4: {
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "15px",
    lineHeight: "22px",
    letterSpacing: "-0.01em",
  },
  h5: {
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "14px",
    lineHeight: "20px",
    letterSpacing: "-0.01em",
  },
  p: {
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "16px",
    lineHeight: "24px",
    letterSpacing: "-0.01em",
  },
  caption: {
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "12px",
    lineHeight: "18px",
    letterSpacing: "-0.01em",
  },
  button: {
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "16px",
    lineHeight: "34px",
    letterSpacing: "-0.01em",
    textTransform: "unset",
    textAlign: "left",
    minWidth: "176px",
  },
};
