import type { Metadata } from "next";
import "./globals.css";
import { inter, red_hat_display } from "@/src/styles/fonts";
import Header from "../components/Header/Header";
export const metadata: Metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${red_hat_display.variable} prose w-full max-w-none`}
    >
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
